### ISSUE TITLE
optional donations for services 

### ISSUE THREAD

**Issue by trozler** [supersaiyanxyz/supersaiyan-contracts#9]
When providers create service they should have the option to specify if they want their service to accept donations. 

In order to for the UI to conditionally render based on this information, we need to store an additional `bool` field in each `Service` struct. 

e.g. 
```
    struct Service {
        address serviceAddress; 
        ServiceState state;
        Counters.Counter packageIds;
        Counters.Counter numPackages; 
        uint256[] subscriptionIds;
        address[] acceptedTokens;
        string name;
        mapping(uint256 => Package) packages; 
        bool acceptsDonations;
    }
```

**Comment by bdim1** [comment]
Sounds good, I will add this field. I just have a question from product perspective if the user should have an option to disable donations and what would be the reason for that (what are the scenarios in which they would want to disable donations)?

**Comment by trozler** [comment]
@bdim1 after conversations with @zant I'm more convinced that our old notion of payment links (single product) should really be divided into 2 separate products:

1. Subscription link
A link that allows user to subscribe using streams powered by superfluid.

2. Payment links
These are links that let users 
- buy me a coffee style.

I'm creating proposal/presentation on this rethink. 
For now I will close issue.
